# Generated by Django 4.0.1 on 2022-01-15 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0005_alter_alloma_allomamenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.alloma')),
            ],
        ),
        migrations.CreateModel(
            name='Subject_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trunk.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Subject_Extra_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trunk.subject_info')),
            ],
        ),
    ]
