# Generated by Django 4.0.1 on 2022-01-14 04:35

import base.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Century',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('century', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Madrasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relevant_century', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.century')),
            ],
        ),
        migrations.CreateModel(
            name='Alloma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images')),
                ('madrasa_alloma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.madrasa')),
            ],
        ),
    ]
