# Generated by Django 4.0.1 on 2022-01-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='century',
            name='sum_madrasa',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
