# Generated by Django 4.0.1 on 2022-01-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_century_sum_madrasa'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllomaMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.AddField(
            model_name='alloma',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='alloma',
            name='birth_area',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='alloma',
            name='birth_year',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='alloma',
            name='allomamenu',
            field=models.ManyToManyField(null=True, to='base.AllomaMenu'),
        ),
    ]
