# Generated by Django 4.0.1 on 2022-01-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_allomamenu_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alloma',
            name='allomamenu',
            field=models.ManyToManyField(blank=True, null=True, to='base.AllomaMenu'),
        ),
    ]
